// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igbpqldarxjzcbgindbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnYnBxbGRhcnhqemNiZ2luZGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjYxNjEsImV4cCI6MjA1ODM0MjE2MX0.sBSh8nDI0CUzzCEVLNew1dm1AUgmSS8L_xxCzDRZCMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);